<?php

require_once '/Users/ivymike/Documents/workspacePHP/NaturalCorner/exceptions/AdresseException.class.php';

/**
 * Test class for ArticleException.
 * Generated by PHPUnit on 2016-04-01 at 16:45:12.
 */
class ArticleExceptionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ArticleException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArticleException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
