<?php

require_once '/Users/ivymike/Documents/workspacePHP/NaturalCorner/actions/EnregistrementAction.inc.php';

/**
 * Test class for EnregistrementAction.
 * Generated by PHPUnit on 2016-04-06 at 00:19:26.
 */
class EnregistrementActionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var EnregistrementAction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER['REQUEST_METHOD'] = 'POST';
        $this->object = new EnregistrementAction;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    /**
     * @covers EnregistrementAction::verifierInput
     * @todo Implement testVerifierInput().
     */
    public function testVerifierInput()
    {
       
       $_POST = array(
              'email' => 'coucou@coucou.be',
              'pwd' => 'coucoU1',
              'pwd2' => 'coucoU1',
              'prenom' => 'coucou',
              'nom' => 'coucou',
              'pseudo' => 'coucou',
              'adresse' => 'coucou',
              'poste' => '1000',
              'localite' => 'coucou'
       );
       $data = $this->object->verifierInput();
       $this->assertEquals('coucou@coucou.be', $data['email']);
       $this->assertEquals('coucoU1', $data['pwd']);
       $this->assertEquals('coucoU1', $data['pwd2']);
       $this->assertEquals('coucou', $data['prenom']);
       $this->assertEquals('coucou', $data['nom']);
       $this->assertEquals('coucou', $data['pseudo']);
       $this->assertEquals('coucou', $data['adresse']);
       $this->assertEquals('1000', $data['poste']);
       $this->assertEquals('coucou', $data['localite']);       
    }

    /**
     * @covers EnregistrementAction::ajouterUtilisateur
     * @todo Implement testAjouterUtilisateur().
     */
    public function testAjouterUtilisateur()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EnregistrementAction::modifierUtilisateur
     * @todo Implement testModifierUtilisateur().
     */
    public function testModifierUtilisateur()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
