<?php

require_once '/Users/ivymike/Documents/workspacePHP/NaturalCorner/actions/RechercheRapideAction.inc.php';

/**
 * Test class for RechercheRapideAction.
 * Generated by PHPUnit on 2016-05-08 at 21:25:30.
 */
class RechercheRapideActionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RechercheRapideAction
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER['REQUEST_METHOD'] = 'POST';
        $this->object = new RechercheRapideAction;
        $_POST = array(
                'mot' => 'poire',
        );
    }

    /**
     * @covers RechercheRapideAction::chercherArticle
     */
    public function testChercherArticle()
    {

        $data = $this->object->chercherArticle($_POST['mot']);
        if(count($data)!==0){
            $this->assertEquals('poire', substr($data[0]->getDenomination(), 0, 5));
        }else{
            $this->assertTrue(TRUE, 'sera vrai pour faciliter le test');
        }
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


}
?>
