<?php

require_once '/Users/ivymike/Documents/workspacePHP/NaturalCorner/model/Commande.class.php';

/**
 * Test class for Commande.
 * Generated by PHPUnit on 2016-05-15 at 14:48:58.
 */
class CommandeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Commande
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Commande;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
