<?php

require_once '/Users/ivymike/Documents/workspacePHP/NaturalCorner/exceptions/UtilisateurException.class.php';
require_once '/Users/ivymike/Documents/workspacePHP/NaturalCorner/model/Utilisateur.class.php';

/**
 * Test class for Utilisateur.
 * Generated by PHPUnit on 2015-12-29 at 19:31:51.
 */
class UtilisateurTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Utilisateur
     */
    protected $utilisateurDuTest;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	$this->utilisateurDuTest = new Utilisateur("Daniel", "Dan", "DanyDan", "Motdepasse1", 
    			"truc@troc.tr", "rue des petites fleurs 5",
    			"1070", "Anderlecht", new DateTime("2015-01-01T00:00:00"), "192.168.0.1");       
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$this->utilisateurDuTest=null;
    }
    /**
     * @covers Utilisateur::getId
     * @todo Implement testGetId().
     */
    public function testGetId()
    {
    	$this->assertEquals($this->utilisateurDuTest->getId(), 0, "devrait afficher 0");
    	
    }
    /**
     * @covers Utilisateur::setId
     * @todo Implement testSetId().
     */
    public function testSetId()
    {
    	$this->utilisateurDuTest->setId(1000);
    	$this->assertEquals($this->utilisateurDuTest->getId(), 1000, "devrait aficher 1000");
    	
    	
    	try{
    		$this->utilisateurDuTest->setId(-1);
    	}catch(UtilisateurException $ue){
    		return;
    	}
    	$this>fail( "aurait dû lancer une exception.");

    }

    /**
     * @covers Utilisateur::getPrenom
     * @todo Implement testGetPrenom().
     */
    public function testGetPrenom()
    {
        
        $this->assertEquals("Daniel", $this->utilisateurDuTest->getPrenom(), "Devrait afficher Daniel");
    }

    /**
     * @covers Utilisateur::setPrenom
     * @todo Implement testSetPrenom().
     */
    public function testSetPrenom()
    { 	
    	// tests du setter
    	// test de l'exception 
    	   
    	try{
    		$this->utilisateurDuTest->setPrenom("NouveauPrenom");
    	}catch(UtilisateurException $ue){
    		
    		$this->fail( "n'aurait pas dû lancer une exception."." ->".$ue);
    	}
    	
    	$this->assertEquals($this->utilisateurDuTest->getPrenom(), "NouveauPrenom", "devrait afficher NouveauPrenom");
    	
    	// test de l'exception : n'accepte pas un string n'ayant pas au moins trois caractères.
    	   
    	try{
    		$this->utilisateurDuTest->setPrenom("da");
    	}catch(UtilisateurException $ue){
    		return;
    	}
    	$this->fail( "aurait dû lancer une exception.");
    	
    	// pas d'alphanumérique
    	
    	try{
    		$this->utilisateurDuTest->setPrenom("dada3");
    	}catch(UtilisateurException $ue){
    		return;
    	}
    	$this->fail( "aurait dû lancer une exception.");
    }

	/**
     * @covers Utilisateur::getNom
     * @todo Implement testGetNom().
     */
    public function testGetNom()
    {
        $this->assertEquals("Dan", $this->utilisateurDuTest->getNom(), "devrait afficher Dan");
    
    }

    /**
     * @covers Utilisateur::setNom
     * @todo Implement testSetNom().
     */
    public function testSetNom()
    {
    	// tests du setter
    	// test de l'exception 
    	   
    	try{
    		$this->utilisateurDuTest->setNom("NouveauNom");
    	}catch(UtilisateurException $ue){
    		
    		$this->fail( "n'aurait pas dû lancer une exception."." ->".$ue);
    	}
    	
    	$this->assertEquals($this->utilisateurDuTest->getNom(), "NouveauNom", "devrait aficher NouveauNom");
    	
    	// test de l'exception : n'accepte pas un string n'ayant pas au moins trois caractères.
    	   
    	try{
    		$this->utilisateurDuTest->setNom("da");
    	}catch(UtilisateurException $ue){
    		return;
    	}
    	$this->fail( "aurait dû lancer une exception.");
    	
    	// pas d'alphanumérique
    	
    	try{
    		$this->utilisateurDuTest->setNom("dada3");
    	}catch(UtilisateurException $ue){
    		return;
    	}
    	$this->fail( "aurait dû lancer une exception.");
    }

    /**
     * @covers Utilisateur::getPseudo
     * @todo Implement testGetPseudo().
     */
    public function testGetPseudo()
    {
        $this->assertEquals("DanyDan", $this->utilisateurDuTest->getPseudo(), "devrait afficher DanyDan");
    }    

    /**
     * @covers Utilisateur::setPseudo
     * @todo Implement testSetPseudo().
     */
    public function testSetPseudo()
    {
       // tests du setter
    	// test de l'exception 
    	   
    	try{
    		$this->utilisateurDuTest->setPseudo("NouveauPseudo");
    	}catch(UtilisateurException $ue){
    		
    		$this->fail( "n'aurait pas dû lancer une exception."." ->".$ue);
    	}
    	
    	$this->assertEquals($this->utilisateurDuTest->getPseudo(), "NouveauPseudo", "devrait aficher NouveauPseudo");
    	
    	// test de l'exception : n'accepte pas un string n'ayant pas au moins trois caractères.
    	   
    	try{
    		$this->utilisateurDuTest->setPseudo("da");
    	}catch(UtilisateurException $ue){
    		return;
    	}
    	$this->fail( "aurait dû lancer une exception.");
    	
    	// pas d'alphanumérique
    	
    	try{
    		$this->utilisateurDuTest->setPseudo("dada3");
    	}catch(UtilisateurException $ue){
    		return;
    	}
    	$this->fail( "aurait dû lancer une exception.");
    }
    /**
     * @covers Utilisateur::getPass
     * @todo Implement testGetPass().
     */
    public function testGetPass()
    {
    	
        $this->assertEquals("Motdepasse1", $this->utilisateurDuTest->getPass(), "devrait afficher motdepasse");
    }


    /**
     * @covers Utilisateur::setPass
     * @todo Implement testSetPass().
     */
    public function testSetPass()
    {
    	//mot de passe avec moins de 6 caractères.
    	try{
    		$this->utilisateurDuTest->setPass("CouC1");
    	}catch(UtilisateurException $ue){
    		return;
    	}
    	$this->fail('aurait dû lancer une exception');
    	
    	//mot de passe sans chiffre et sans majuscule.
    	try{
    		$this->utilisateurDuTest->setPass("passtest");
    	}catch(UtilisateurException $ue){
    		return;
    	}
        $this->fail('aurait dû lancer une exception');
        
        // mot de passe uniquement avec des majuscules.
        try{
        	$this->utilisateurDuTest->setPass("PASSTEST");
        }catch(UtilisateurException $ue){
        	return;
        }
        $this->fail('aurait dû lancer une exception');
        
        //mot de passe uniquement avec des chiffres.
        try{
        	$this->utilisateurDuTest->setPass("01222324234");
        }catch(UtilisateurException $ue){
        	return;
        }
        $this->fail('aurait dû lancer une exception');
        
        //mot de passe avec au moins une majuscule, une minuscule et un chiffre.
        $this->utilisateurDuTest->setPass("coucoucoU1");
        $this->assetEquals("coucoucoU1", $this->utilisateurDuTest->getPass());
        
        //mot de passe avec deux majuscules, une minuscule et un chiffre.
        $this->utilisateurDuTest->setPass("coUcoucoU1");
        $this->assetEquals("coucoucoU1", $this->utilisateurDuTest->getPass());
        
        //mot de passe avec deux majuscules, une minuscule et deux chiffres.
        $this->utilisateurDuTest->setPass("coUcoucoU12");
        $this->assetEquals("coucoucoU1", $this->utilisateurDuTest->getPass());
    }


    /**
     * @covers Utilisateur::getAdresseMail
     * @todo Implement testGetAdresseMail().
     */
    public function testGetAdresseMail()
    {
        $this->assertEquals("truc@troc.tr", $this->utilisateurDuTest->getAdresseMail(), "devrait afficher truc@troc.tr");
    }
    /**
     * @covers Utilisateur::setAdresseMail
     * @todo Implement testSetAdresseMail().
     */
    public function testSetAdresseMail()
    {
        $this->utilisateurDuTest->setAdresseMail("nouvelleAdresse@test.com");
        
        $this->assertEquals("nouvelleAdresse@test.com", $this->utilisateurDuTest->getAdresseMail(), "devrait afficher nouvelleAdresse@test.com");
    }


	/**
     * @covers Utilisateur::getAdressePhysique
     * @todo Implement testGetAdressePhysique().
     */
    public function testGetAdressePhysique()
    {
        $this->assertEquals("rue des petites fleurs 5", $this->utilisateurDuTest->getAdressePhysique(), 
        		"devrait afficher rue des petites fleurs 5");
    	
    }
    /**
     * @covers Utilisateur::setAdressePhysique
     * @todo Implement testSetAdressePhysique().
     */
    public function testSetAdressePhysique()
    {
        try{
             $this->utilisateurDuTest->setAdresseMail("Rue de l'indépendance 23");
        }catch(UtilisateurException $ue){
            return;
        }
         $this->assertEquals("Rue de l'indépendance 23", $this->utilisateurDuTest->getAdressePhysique(),
                 "Rue de l'indépendance 23");
    }

     /**
     * @covers Utilisateur::getCodePostal
     * @todo Implement testGetCodePostal().
     */
    public function testGetCodePostal()
    {
        $this->assertEquals("1070", $this->utilisateurDuTest->getCodePostal(), "devrait afficher 1070");
    	
    }

    /**
     * @covers Utilisateur::setCodePostal
     * @todo Implement testSetCodePostal().
     */
    public function testSetCodePostal()
    {
        $this->utilisateurDuTest->setCodePostal("1030");
        $this->assertEquals("1030", $this->utilisateurDuTest->getCodePostal(), "devrait afficher 1030");
        
    }

   
    /**
     * @covers Utilisateur::getLocalite
     * @todo Implement testGetLocalite().
     */
    public function testGetLocalite()
    {
        $this->assertEquals("Anderlecht", $this->utilisateurDuTest->getLocalite(), "devrait afficher Anderlecht");
    	
    }
    /**
     * @covers Utilisateur::setLocalite
     * @todo Implement testSetLocalite().
     */
    public function testSetLocalite()
    {
        $this->utilisateurDuTest->setLocalite("Schaerbeek");
        $this->assertEquals("Schaerbeek", $this->utilisateurDuTest->getLocalite(), "devrait afficher Schaerbeek");
    }
    /**
     * @covers Utilisateur::getDateInscription
     * @todo Implement testGetDateInscription().
     */
    public function testGetDateInscription()
    {
    	
        $this->assertEquals((new DateTime("2015-01-01T00:00:00"))->format('Y-m-d H:i:s'), 
        		$this->utilisateurDuTest->getDateInscription(), "devrait afficher 2015-01-01 00:00:00");
    	
    }
    
    /**
     * @covers Utilisateur::setDateInscription
     * @todo Implement testSetDateInscription().
     */
    public function testSetDateInscription()
    {
        $this->utilisateurDuTest->setDateInscription(new DateTime("2016-01-01T00:00:00"));
        $this->assertEquals((new DateTime("2016-01-01T00:00:00"))->format('Y-m-d H:i:s'),
            $this->utilisateurDuTest->getDateInscription(), "devrait afficher 2016-01-01 00:00:00");
    }
    /**
     * @covers Utilisateur::getIdConnexion
     * @todo Implement testGetIdConnexion().
     */
    public function testGetIdConnexion()
    {
        $this->assertEquals("192.168.0.1", $this->utilisateurDuTest->getIdConnexion(), "devrait afficher 192.168.0.1");
    	
    }

    /**
     * @covers Utilisateur::setIdConnexion
     * @todo Implement testSetIdConnexion().
     */
    public function testSetIdConnexion()
    {
        $this->utilisateurDuTest->setIdConnexion("127.0.0.1");
        $this->assertEquals("127.0.0.1", $this->utilisateurDuTest->getIdConnexion(), "devrait afficher 127.0.0.1");
        
    }
    /**
     * @covers Utilisateur::__toString()
     */
    public function testToString()
    {
    	$stringUtilisateur = $this->utilisateurDuTest->__toString();
    	$this->assertEquals('{"id"="0","prenom"="Daniel","nom"="Dan","pass"="Motdepasse1","adresseMail"="truc@troc.tr","adressePhysique"="rue des petites fleurs 5"'.
    	        ',"codePostal"="1070","localite"="Anderlecht","dateInscription"="2015-01-01 00:00:00","ipConnexion"="192.168.0.1"}', $stringUtilisateur);
    }
}
?>
$this->utilisateurDuTest = new Utilisateur("Daniel", "Dan", "DanyDan", "Motdepasse1", 
    			"truc@troc.tr", "rue des petites fleurs 5",
    			"1070", "Anderlecht", new DateTime("2015-01-01T00:00:00"), "192.168.0.1");       