<?php

require_once '/Users/ivymike/Documents/workspacePHP/NaturalCorner/model/Vendeur.class.php';
require_once '/Users/ivymike/Documents/workspacePHP/NaturalCorner/model/Utilisateur.class.php';


/**
 * Test class for Vendeur.
 * Generated by PHPUnit on 2016-04-01 at 23:29:09.
 */
class VendeurTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Vendeur
     */
    protected $vendeur;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->vendeur = new Vendeur("Daniel", "Dan", "DanyDan", "Motdepasse1", 
    			"truc@troc.tr", "rue des petites fleurs 5",
    			"1070", "Anderlecht", new DateTime("2015-01-01T00:00:00"), "192.168.0.1");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->vendeur);
    }
    /**
     * @covers Utilisateur::getId
     */
    public function testInheritance()
    {
        $this->assertTrue($this->vendeur instanceof Utilisateur);
         
    }
    
    /**
     * @covers Utilisateur::getId
     */
    public function testGetId()
    {
        $this->assertEquals($this->vendeur->getId(), 0, "devrait afficher 0");
         
    }
    /**
     * @covers Utilisateur::setId
     */
    public function testSetId()
    {
        $this->vendeur->setId(1000);
        $this->assertEquals($this->vendeur->getId(), 1000, "devrait aficher 1000");
         
         
        try{
            $this->vendeur->setId(-1);
        }catch(UtilisateurException $ue){
            return;
        }
        $this>fail( "aurait dû lancer une exception.");
    
    }
    
}
?>
